// IPCamX.idl : source de la bibliothèque de types pour le projet de contrôle ActiveX.

// Ce fichier sera traité par l'outil Compilateur MIDL pour
// produire la bibliothèque de types (IPCamX.tlb) qui deviendra une ressource dans
// IPCamX.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(76653516-8B43-46EF-870B-EDD2B10D6007), version(1.0),
  helpfile("IPCamX.hlp"),
  helpstring("Module de contrôle ActiveX IPCamX"),
  control ]
library IPCamXLib
{
	importlib(STDOLE_TLB);

	//  Interface de dispatch principale pour CIPCamXCtrl

	[ uuid(45D7D8C8-E87B-4799-9E4B-4AB504E64F8E),
	  helpstring("Interface de dispatch pour IPCamX Control")]
	dispinterface _DIPCamX
	{
		properties:
			[id(2) , helpstring("propriété Width")] LONG Width;
			[id(3) , helpstring("propriété Height")] LONG Height;
			[id(5) , helpstring("propriété Source")] BSTR Source;
			[id(6), helpstring("propriété Playing")] VARIANT_BOOL Playing;
			[id(12), helpstring("propriété FPS")] DOUBLE FPS;
			[id(13) , helpstring("propriété Update")] VARIANT_BOOL Update;
			[id(16) , helpstring("propriété Timeout")] LONG Timeout;
			[id(17), helpstring("propriété Index")] LONG Index;
			[id(19) , helpstring("propriété Wait")] VARIANT_BOOL Wait;
	methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
			[id(9), helpstring("méthode Initialize")] LONG Initialize(void);
			[id(10), helpstring("méthode Finalize")] LONG Finalize(void);
			[id(15), helpstring("méthode GetImageOpenCV")] LONG GetImageOpenCV(void);
			[id(18), helpstring("méthode Configure")] LONG Configure(LONG Timeout);
			[id(20), helpstring("méthode Unconfigure")] LONG Unconfigure(void);
			[id(21), helpstring("méthode GetImageLabVIEW")] LONG GetImageLabVIEW(LONG* pData);
	};

	//  Interface de dispatch d'événement pour CIPCamXCtrl

	[ uuid(9D08856C-694B-4170-9FD4-41BF7612A99C),
	  helpstring("Interface d'événement pour IPCamX Control") ]
	dispinterface _DIPCamXEvents
	{
		properties:
			//  L'interface d'événement n'a pas de propriété

		methods:
	};

	//  Informations de classe pour CIPCamXCtrl

	[ uuid(E9FBB53F-3373-4568-A7D3-D0E160EAF912),
	  helpstring("IPCamX Control"), control ]
	coclass IPCamX
	{
		[default] dispinterface _DIPCamX;
		[default, source] dispinterface _DIPCamXEvents;
	};

};
